services:
  auth-api:
    container_name: authenticator_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # IMPORTANT: Note 'Server=db'. This matches the service name above.
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=authprojectdb;Uid=root;Pwd=CoeUnb83!;

  db:
    image: mysql:8.0
    container_name: auth_db
    restart: always
    environment:
      MYSQL_DATABASE: authprojectdb
      MYSQL_ROOT_PASSWORD: CoeUnb83!
    ports:
      - "3307:3306" # Map Host 3307 to Container 3306 (to avoid conflict with local MySQL)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: